name: Deploy Voting System on push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Get the latest code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer Dependencies
        run: composer install --optimize-autoloader --no-dev --no-progress --prefer-dist

      - name: Set appropriate permissions
        run: |
          chmod -R 755 storage
          chmod -R 755 bootstrap/cache

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_VOTING_SERVER }}
          username: ${{ secrets.FTP_VOTING_USERNAME }}
          password: ${{ secrets.FTP_VOTING_PASSWORD }}
          protocol: ${{ secrets.FTP_VOTING_PROTOCOL }}
          port: ${{ secrets.FTP_VOTING_PORT }}
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/tests/**
            .github
            phpunit.xml
            LICENSE
            README.md